---
title: Analysis of CFTR variants
author: Elena Núñez Tomás
output: html_document
email_address: elena.nt.bioinf@gmail.com
github_repo: https://github.com/elenantbioinf/poc_cf
params:
    final_report_json: NULL
---

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">


```{css echo=FALSE}
.author, .title {
    display: none;
}
.main-container{
    max-width: 100%;
}
body {
    background-color: white;
    color: black;
    font-family: "Montserrat", sans-serif;
}
pre {
    background-color: #f4f4f4;
    padding: 15px;
    border-radius: 6px;
}
```

```{r echo=FALSE}
library(jsonlite)

data <- fromJSON(params$final_report_json)

sample_id <- data$sample_id
disease   <- data$disease
gene      <- data$gene
reference    <- data$reference_genome

total_variants <- data$summary$total_unique_variants
variants <- data$variants
no_variants <- (total_variants == 0)
```

# CFTR Variant Report
## Sample information

Sample ID: `r sample_id`

Disease: `r disease`

Gene: `r gene`

Reference genome: `r reference`

## Variants detected

Total unique variants: `r total_variants`

```{r echo=FALSE, results="asis"}
if (no_variants) {
  cat("No variants detected in your analysis.\n")
} else {
  for (i in seq_len(nrow(variants))) {
    v <- variants[i, ]

    cat(sprintf("\n### Variant: %s\n\n", v$input_variant))
    cat(sprintf("- Best annotation: %s\n", v$best_annotation))
    cat(sprintf("- Gene: %s\n", v$gene))
    cat(sprintf("- Transcript: %s\n", v$transcript))
    cat(sprintf("- Exon: %s\n", v$exon))
    cat(sprintf("- Consequence: %s\n", v$consequence))
    cat(sprintf("- Impact: %s\n", v$impact))
    cat(sprintf("- HGVS_C: %s\n", v$hgvs_c))
    cat(sprintf("- Protein: %s\n", v$protein))
    cat(sprintf("- Transcript annotations (rows): %s\n\n", v$transcript_annotations_rows))
  }
}
```
