
#################This is the config.yml############################################
# Samples
samples_table: "config/samples.tsv"


#############################################################
# Reference genome
reference:
  #local path where the reference genome in fasta will be stored
  fasta: "data/reference/hg38.fa"
  #url to download the reference genome if don't use local
  url:


##############################################################
paths:
  #local path for the raw data
  raw_reads: "data/raw"
  #sequencing type
  paired_end: true
  #local path for the clean data (after trimming)
  clean_reads: "data/clean"
  #path for the trimming results
  preprocessing_results: "results/preprocessing"

##############################################################
# Trimming params
trimming: 
  #trim by lenght
  min_length: 30