
#################This is the config.yml############################################
# Samples
samples_table_path: "config/samples.tsv"


#############################################################
# Reference genome
reference:
  #local path where the reference genome in fasta will be stored
  fasta: "data/reference/hg38.fa"
  #url to download the reference genome
  url: "ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"


##############################################################
paths:
  #local path for the raw data
  raw_reads: "data/raw"
  #sequencing type
  paired_end: true
  #local path for the clean data (after trimming)
  clean_reads: "data/clean"
  #path for the trimming results
  preprocessing_results: "results/preprocessing"


##############################################################
01_quality_control:
  raw_fastqc_dir: "results/quality_control/raw_fastqc"
  raw_multiqc_dir: "results/quality_control/raw_multiqc"


##############################################################
# Trimming params
trimming: 
  #trim by lenght
  min_length: 30